export type Translations = typeof translations;

const translations = {
    // Navbar
    aboutUs: 'About Us',
    news: 'News',
    products: 'Products',
    contacts: 'Contacts',
    shop: 'Shop',
    // HomePage
    homePageHeader: "Leading company in the production of polymer packaging",
    contactUs: "Contact Us",
    ourProducts: "Our Products",
    ourProductsDescription: "Discover our full range of high-quality polymer products designed for various industrial applications.",
    ourProductsButton: "View All Products",

    product1_name: 'AGROLEN® Three-Layer Polyethylene Greenhouse Film',
    product1_description: 'AGROLEN® is a high-quality three-layer polyethylene film designed for professional greenhouses. Provides excellent light transmission, optimal microclimate, and high resistance to weather conditions. Suitable for year-round use and effective crop protection.',
    product1_features: 'UV stabilization for long life, Optimal light transmission, Anti-condensation effect (anti-drip), Increased mechanical strength, Improved thermal insulation',
    product1_applications: 'Greenhouses, Tunnels, Winter gardens, Crop protection',
    product1_category: 'Greenhouses',
    product2_name: 'Polyethylene Films and Packaging',
    product2_description: '“HIK-91” is a leading manufacturer of polyethylene films and packaging—products designed to ensure reliable protection, ease of use, and long-lasting performance in all conditions. We provide solutions that meet the high requirements of agriculture and industry.',
    product2_features: 'Variety of formats (sleeve/half-sleeve/sheet), Printing and perforation options, Different thicknesses and widths, High chemical resistance, Custom sizes',
    product2_applications: 'Industrial packaging, Palletizing, Construction, Agriculture, Logistics',
    product2_category: 'Packaging',
    product3_name: 'Polypropylene Woven Bags',
    product3_description: '“HIK-91” is a leading manufacturer of polypropylene woven bags, suitable for all mass applications.',
    product3_description_title: 'What are they?',
    product3_description_body: 'Polypropylene woven bags are made from thin PP tape that is woven into a strong fabric structure. The result is a lightweight, durable package resistant to mechanical loads, intended for storage and transport of various bulk materials.\n\nPolypropylene woven bags are produced in sizes with widths from 30 to 85 cm and lengths from 45 to 135 cm. The fabric can be made in different weights per m².',
    product3_benefits_title: 'What are their advantages?',
    product3_benefits_body: 'Polypropylene woven bags are a preferred option for packaging and transporting goods due to their practicality. Lightweight and easy to transport for various bulk goods. Key qualities include high durability, as well as the ability for repeated use and recycling. Polypropylene bags provide good ventilation, making them especially suitable for storing grain, feed, and other agricultural products.\n\nWe also offer branding with printing up to 4 colors.',
    product3_applications_title: 'Where is it used?',
    product3_applications_chip1: 'Grains',
    product3_applications_chip2: 'Feed',
    product3_applications_chip3: 'Construction materials',
    product3_applications_chip4: 'Chemicals',
    product3_applications_chip5: 'Fertilizers',
    product3_applications_intro: 'Ideal for packaging and transporting a wide range of bulk products, including animal feed, grains, flour and sugar, fertilizers, as well as various bulk and granulated products.',
    product3_features: 'High mechanical strength, Low weight, Reusable, Lamination and printing options, Various sizes',
    product3_applications: 'Grains, Feed, Construction materials, Chemicals, Fertilizers',
    product3_category: 'Bags',
    product4_name: 'Non-Woven Fabric – Spunbond',
    product4_description: '“HIK-91” produces non‑woven fabric (Spunbond) made from 100% polypropylene, with widths up to 2.4 m and weights from 15 to 100 g/m². The material can be white or colored, with UV stabilization if needed, and with the option for bonding up to 12 m width, which allows its use over large areas, mainly in agriculture.',
    product4_features: 'High permeability, UV stabilization, Lightweight construction, Tear-resistant, Easy installation',
    product4_applications: 'Mulching, Weed control, Frost protection, Geotextile, Filtration',
    product4_category: 'Nonwoven fabric',
    product5_name: 'Polypropylene Twisted Ropes/Sisal for Baling and Tying',
    product5_description: '“HIK-91” produces high‑quality polypropylene twisted ropes (sisal) from polypropylene tapes. Products in this category stand out with strength, uniform yarn thickness, and excellent load resistance. The sisal ropes are offered in various thicknesses and colors, with an option for UV stabilization.',
    product5_features: 'High tensile strength, UV resistant, Low weight, Low stretch, Long service life',
    product5_applications: 'Hay baling, Plant tying, Construction, General tying',
    product5_category: 'Ropes',
    product6_name: 'Regranulate Products',
    product6_description: '“HIK-91” produces a wide range of products made from regranulate (recycled polyethylene) - film, sleeves, and bags. Recycling takes place on site, and the resulting regranulate is used in our products. Regranulate products are a practical and economical solution for various industrial and technical applications.',
    product6_features: 'Eco-friendly choice, Optimal price/quality ratio, Wide range of applications, Recyclable',
    product6_applications: 'Packaging solutions, Construction materials, Technical products',
    product6_category: 'Regranulate',

    testimonial1_content: "I am extremely satisfied with the quality and fast delivery! I recommend it to every farmer.",
    testimonial1_author: "Ivan Petrov",
    testimonial1_role: "Farmer",
    testimonial2_content: "The products are really durable and practical. The service was top-notch!",
    testimonial2_author: "Maria Georgieva",
    testimonial2_role: "Greenhouse Owner",
    testimonial3_content: "I am happy with the prices and the personal attention. I will order again!",
    testimonial3_author: "Georgi Dimitrov",
    testimonial3_role: "Customer",
    testimonial4_content: "Fast delivery and excellent service! I will recommend it to my colleagues.",
    testimonial4_author: "Stefka Ivanova",
    testimonial4_role: "Farmer",
    testimonial5_content: "I am very satisfied with the products and will order again!",
    testimonial5_author: "Petar Kolev",
    testimonial5_role: "Farmer",
    testimonialsHeader: 'What Our Customers Say',
    testimonialsSubHeader: 'Don’t just take our word for it. See what real customers share about our products and service.',
    testimonial_no_comment: 'Rating only (no comment).',
    // Foooter
    quickLinks: 'Quick Links',
    email: 'Email',
    address: 'Address',
    phone: 'Phone',
    ourAddress: 'Sadovo, 15 km from Plovdiv',
    ourRights: '© 2025 HIK-91. All rights reserved.',
    // AboutUsPage
    aboutUsSection1Title: 'What do we do?',
    aboutUsSection1Body: 'We produce a wide range of polymer products—films, packaging, and regranulate items. Our solutions are used in agriculture, construction, food processing, and more.\n• AGROLEN® professional greenhouse film—specialized for greenhouses;\n• Various polyethylene films and packaging—single- and double-slit films, sleeves, and bags in different thicknesses and sizes;\n• Polypropylene woven bags—various sizes, white or printed up to 4 colors;\n• Non-woven fabric (spunbond)—different weights per sq. m., suitable for agricultural and industrial applications;\n• Polypropylene twisted ropes/sisal for baling and tying—durable, stable, and resilient under load;\n• Regranulate products—eco-friendly solutions for industrial and household needs.\nAll our products are manufactured to standard and to the customer’s individual requirements.',
    aboutUsSection2Title: 'Who are we?',
    aboutUsSection2Body: '“HIK-91” is a Bulgarian manufacturer with over 30 years of experience in producing high-quality polymer packaging and films.\nWe started in 1991 as a small family business, driven by one goal—to create reliable products that help businesses grow.\nToday, “HIK-91” operates a modern production facility in Sadovo, certified to international quality and safety standards.\nWe invest in sustainability, innovation, and continuous control at every stage of polymer film and packaging production.',
    aboutUsSection3Title: 'Why trust us?',
    aboutUsSection3Body: 'For us, every solution we offer is a promise of efficiency. Here is what makes us different:\n• Experience and stability—over 30 years of work have established us as a reliable partner businesses can depend on;\n• High quality standards—we have implemented ISO 9001 and ISO 14001 certifications that guarantee reliability, safety, and responsibility to the environment;\n• Modern production capabilities—we use contemporary equipment and invest in upgrading our production lines;\n• Flexibility and a broad product range—we offer a rich product assortment.',

    statCardLabel1: 'Years of Experience',
    statCardLabel2: 'Satisfied Customers',
    statCardLabel3: 'ISO Certificates',

    ourCertificates: 'Our Certificates',
    certificateSubHeader: 'Quality and reliability are at the core of our work',
    certificate1Subtitle: 'Quality Management System',
    certificate1Note: 'We guarantee high quality for all our products and services',
    certificate2Subtitle: 'European certification for recycling companies',
    certificate2Note: 'Certified management and traceability in recycling',
    certificate3Subtitle: 'Environmental Management System',
    certificate3Note: 'We protect the environment through responsible production',

    timeline1: 'Establishment of "HIK-91"; the company had one extruder for single-layer film.',
    timeline2: 'Started production of single-layer film up to 8m width.',
    timeline3: 'Installation of extruder for polyethylene bags.',
    timeline4: 'Started production of polypropylene ropes (sisal).',
    timeline5: 'Started production of film up to 12m width.',
    timeline6: 'Installation of complete equipment for production of standard PP bags.',
    timeline7: 'Started production of polypropylene woven bags type AD Star®, with printing capability up to 4 colors.',
    timeline8: 'Installation of extruder for polyethylene film; single-layer film replaced by three-layer film up to 14 meters wide.',
    timeline9: 'Installation of equipment for production of three-layer film up to 8m, heavy-grade sisal; installation of heavy-grade looms for producing Big Bags woven fabric.',
    timeline10: 'Installation of a complete recycling line, as well as a machine for polyethylene bags and garbage bags.',
    timeline11: 'Installation of a new line for production of polypropylene ropes (sisal), and increase of recycling capacity.',
    timeline12: 'Start of a new line for nonwoven fabric production (Spunbond), and a new extruder line for multilayer film up to 6 meters wide.',

    //NewsPage
    news1Content: 'The company “HIK-91 - PATSEV & CO” SD has started the implementation of a grant agreement under procedure: BG-RRP-3.004 “Technological Modernization”. The project is carried out with the financial support of the National Recovery and Resilience Plan, co-financed by the European Union.',
    news1File1: 'Download the full text HERE',
    news2Content: 'HIK-91 participates in project № BG16RFOP002-2.077-1361-C01 titled:',
    news2File1: '“Support for medium-sized enterprises to overcome the economic consequences of the COVID-19 pandemic”',
    news3Content: '“HIK-91 - PATSEV & CO” SD announces a procedure for selecting a contractor under Art.2 (1) of Decree № 80/09.05.2022 with subject: “Supply, installation and commissioning of an Ultrasonic machine for welding and rewinding nonwoven fabric - 1 unit.” Deadline for submission of offers - 14.12.2022 (23:59).',
    news3SubHeader1: 'Offers are submitted in ISUN, section “E-procurement procedures”:',
    news3File1: 'ISUN – E-procurement procedures',
    news3SubHeader2: 'Application documents (available from the news page):',
    news3File2: 'Public invitation',
    news3File3: 'Requirements',
    news3File4: 'Offer template',
    news3File5: 'Evaluation methodology',
    news3File6: 'EIK declaration',
    news3File7: 'Applicants declaration',
    news3File8: 'Draft execution contract',
    news3File9: 'Annex 2 to execution contract',
    news3File10: 'Technical specification',

    //ContactsPage
    contactQuestions: 'Contact us for inquiries, quotes, and collaboration',
    sendUsMessage: 'Send us a message',
    name: 'Name',
    theme: 'Subject',
    message: 'Message',
    sendMessage: 'Send message',
    yourMessage:'Your message...',
    yourName:'Your Name',
    youCanFindUsHere: 'You can find us here',
    ourOffices: 'Our offices',
    tel: 'tel.:',
    office1: 'Head office - 4122 Sadovo, Agricultural yard, tel.:',
    office2: 'Karnalovo, area "Chukito-2"',
    office2Line2: 'Agrocomplex in Karnalovo — tel.:',
    office3: 'Plovdiv, 2A "Georgi Tringov" St. – tel.:',
    office4: 'Blagoevgrad, 5 Anton Chekhov St.,',
    office4Line2:'Wholesale trade "Pirin Commerce" – tel.:',
    office5: 'Varna, 39 "Kolyo Ficheto" St., warehouse 23 – tel.:',
    chooseTheme: 'Choose a theme',
    theme1: 'General inquiries',
    theme2: 'Product information',
    theme3: 'Pricing and offers',
    theme4: 'Delivery',
    theme5: 'Partnership',
    theme6: 'Other',

    // ProductsPage

    product1_application1: 'Greenhouses',
    product1_application2: 'Tunnels',
    product1_application3: 'Winter Gardens',
    product1_application4: 'Plant Protection',
    product1_feature1: 'UV stabilization for long life',
    product1_feature2: 'Optimal light transmission',
    product1_feature3: 'Anti-condensation effect (anti-drip)',
    product1_feature4: 'Enhanced mechanical durability',
    product1_feature5: 'Improved thermal insulation',
    product1_description_title: 'What is it?',
    product1_description_body: 'AGROLEN® is a high‑tech polyethylene film developed specifically for professional greenhouse production. Unlike standard single‑layer films, AGROLEN® combines three functional layers with different additives—for durability, thermal insulation, and moisture control. This structure provides a significantly longer service life, better crop protection, and optimal growing conditions in every season.',
    product1_specs_description_title: 'What are its advantages?',
    product1_specs_description: 'AGROLEN® professional greenhouse film stands out with:',
    product1_longDescription: 'AGROLEN® is a three-layer film designed to provide controlled light transmission and stable internal climate in greenhouses. Special additives reduce drip-like condensation (anti-drip), improve light scattering, and increase mechanical durability. It is suitable for vegetable, flower, and seedling production, as well as for covering tunnels and greenhouses.',
    product1_specs_label: 'Structure',
    product1_specs_labe2: 'Light Transmission',
    product1_specs_labe3: 'UV Stabilization',
    product1_specs_labe4: 'Available Widths',
    product1_specs_labe5: 'Application',
    product1_specs_labe6: 'UV blocking and pest protection',
    product1_specs_labe7: 'Functional C-fold',
    product1_specs_value1: 'Three-layer PE',
    product1_specs_value2: 'High',
    product1_specs_value3: 'Long-lasting',
    product1_specs_value4: 'Upon request',
    product1_specs_value5: 'Greenhouses, tunnels, winter gardens',
    product1_specs_value6: 'The UV blocking effect reduces pest populations like whitefly and spider mites by disrupting their orientation and reproduction.',
    product1_specs_value7: 'Enables easy and quick laying of the film without twisting or edge damage, resulting in a compact roll and less effort during installation.',
    product1_applications_title: 'Where is it used?',
    product1_applications_intro: 'AGROLEN® professional greenhouse film is used for building:',
    product1_applications_item1: 'Greenhouses and tunnels (seasonal and year-round);',
    product1_applications_item2: 'Agricultural tunnels;',
    product1_applications_item3: 'Professional farming projects and modern agro holdings.',
    product1_applications_outro: 'AGROLEN® is a solution for growers seeking maximum productivity and better microclimate control in greenhouses.',

    // Product 2
    product2_application1: 'Industrial Packaging',
    product2_application2: 'Palletizing',
    product2_application3: 'Construction Activities',
    product2_application4: 'Agriculture',
    product2_application5: 'Logistics',
    product2_feature1: 'Variety of formats (sleeve/half-sleeve/sheet)',
    product2_feature2: 'Option for printing and perforation',
    product2_feature3: 'Different thicknesses and widths',
    product2_feature4: 'High chemical resistance',
    product2_feature5: 'Custom sizes',
    product2_longDescription: 'Our polyethylene films and packaging are made to specification – sleeve, half-sleeve, or sheet, with the possibility of printing, perforation, and antistatic additives. They are suitable for protecting and packaging items, covering and cladding pallets, temporary shelters, as well as for applications in construction and agriculture.',
    product2_types_title: 'What polyethylene films and packaging do we produce?',
    product2_types_intro: 'We offer a wide range of polyethylene films and packaging, developed to meet specific business needs and the highest industry standards. Our catalog includes the following main types:',
    product2_types_item1_title: 'Greenhouse films',
    product2_types_item1_body: 'size per customer request, with widths up to 14 m; Types: AGROLEN®, polyethylene film without additives, green-tinted film with UV stabilization, natural film with UV stabilization; Optional additives: UV stabilization, Infrared (IR), Anti-drip (AF), Anti-fog (AM), EVA.',
    product2_types_item2_title: 'Other films for use in greenhouses:',
    product2_types_item2_body: '',
    product2_types_item2_sub1: 'black-and-white and white films for laying on the floor in hydroponic greenhouses',
    product2_types_item2_sub2: 'partition film with or without perforation to reduce heated volume in winter',
    product2_types_item3_title: 'Shrink film',
    product2_types_item3_body: 'sleeve or double-slit film and shrink covers; transparent or colored; modifications: with UV stabilization and additives to meet specific customer needs.',
    product2_types_item4_title: 'Silage film',
    product2_types_item4_body: 'width 6 to 14 m; thickness 125 to 200 microns; one-year UV stabilization (1 year); provides good mechanical properties and strong resistance to tearing and blowing. Very low oxygen permeability. Excellent barrier to water and air; Color combinations: black, black-silver/white, black-green;',
    product2_types_item5_title: 'Polyethylene sleeves',
    product2_types_item5_body: 'various sizes per customer request; transparent or colored;',
    product2_types_item6_title: 'Polyethylene bags',
    product2_types_item6_body: 'various sizes per customer request',
    product2_types_item7_title: 'Mulch film',
    product2_types_item7_body: 'film with direct contact with the soil; UV stabilization; Color combinations: transparent, black, white/black.',
    product2_applications_title: 'Where are our products used?',
    product2_applications_intro: 'Our polyethylene films and packaging have universal and/or specific applications depending on their type:',
    product2_applications_item1: 'For agricultural needs (crop farming and livestock);',
    product2_applications_item2: 'For packaging pallets, loads, and products of various sizes in the glass, chemical, ceramic, and food industries;',
    product2_applications_item3: 'Films for covering feed and grain, preserving their nutritional properties for livestock consumption;',
    product2_applications_item4: 'In the chemical and food industries, for bulk materials;',
    product2_applications_item5: 'Mulch films are placed directly on the soil to stop weed growth, increase yields, reduce the need for irrigation, and improve crop condition.',
    product2_specs_label1: 'Material',
    product2_specs_label2: 'Formats',
    product2_specs_label3: 'Thicknesses',
    product2_specs_label4: 'Options',
    product2_specs_value1: 'LDPE/HDPE upon request',
    product2_specs_value2: 'Sleeve, half-sleeve, sheet',
    product2_specs_value3: 'Upon request',
    product2_specs_value4: 'Printing, perforation, additives',

    // Product 3
    product3_application1: 'Grains',
    product3_application2: 'Animal Feed',
    product3_application3: 'Building Materials',
    product3_application4: 'Chemicals',
    product3_application5: 'Fertilizers',
    product3_feature1: 'High mechanical strength',
    product3_feature2: 'Low weight',
    product3_feature3: 'Reusable',
    product3_feature4: 'Option for lamination and printing',
    product3_feature5: 'Various sizes',
    product3_longDescription: 'PP woven bags are intended for transporting and storing grains and other bulk materials. They are produced in various sizes, with the option for lamination for better moisture protection and printing for content identification. They are distinguished by high strength and good wear resistance.',
    product3_specs_label1: 'Material',
    product3_specs_label2: 'Options',
    product3_specs_label3: 'Sizes',
    product3_specs_label4: 'Application',
    product3_specs_value1: 'PP (woven)',
    product3_specs_value2: 'Lamination, print',
    product3_specs_value3: 'Upon request',
    product3_specs_value4: 'Grains, animal feed, building materials',

    // Product 4
    product4_application1: 'Mulching',
    product4_application2: 'Weed Control',
    product4_application3: 'Frost Protection',
    product4_application4: 'Geotextile',
    product4_application5: 'Filtration',
    product4_feature1: 'High permeability',
    product4_feature2: 'UV stabilization',
    product4_feature3: 'Lightweight construction',
    product4_feature4: 'Tear resistance',
    product4_feature5: 'Easy installation',
    product4_longDescription: 'Nonwoven frost protection fabric (Agril) is a breathable, lightweight, UV-stabilized material that protects plants from freezing, wind, and direct sunlight. It is used for direct covering of beds and crops, allowing air and water to pass through without disrupting the microclimate. It is suitable for both early spring and late autumn production. The material helps reduce plant stress and accelerates growth. Due to good thermal insulation and permeability, it helps maintain stable conditions around the crops.',
    product4_specs_label1: 'Color',
    product4_specs_label2: 'Weight',
    product4_specs_label3: 'UV Protection',
    product4_specs_label4: 'Example Widths',
    product4_specs_label5: 'Typical Roll Length',
    product4_specs_value1: 'White',
    product4_specs_value2: '23 g/m²',
    product4_specs_value3: 'For 1 year',
    product4_specs_value4: '1.6m, 2m, 3.2m, 4m, 6m, 8m, 10m',
    product4_specs_value5: '12m (example)',
    product4_description_title: 'What is it?',
    product4_description_body: 'Non‑woven fabric (Spunbond) is produced by extruding polypropylene fibers, followed by uneven laying and bonding of the fibers. The material does not let dust through, but allows air to pass, making it suitable for industrial, medical, and agricultural applications. Its surface is smooth and pleasant to the touch, it does not become electrostatic, and it can be produced in different colors and with additional functionalities such as UV stabilization.\n\nThanks to this production process, Spunbond fabric combines high strength, low weight, and durability over time.',
    product4_applications_title: 'Where is it used?',
    product4_applications_intro: 'Non‑woven fabric is highly versatile and is used in many industries such as:',
    product4_applications_item1: 'Furniture and tailoring industry – for linings, coverings, interior elements, and more;',
    product4_applications_item2: 'Agriculture – crop protection from frost, insects, and UV rays;',
    product4_applications_item3: 'Medical products – for manufacturing disposable protective masks, gowns, and other single‑use medical garments;',
    product4_applications_item4: 'Filtration – as a layer in various filtration systems;',
    product4_applications_item5: 'Packaging – protective, decorative, or technical packaging for a wide range of goods.',
    product4_benefits_title: 'What are its advantages?',
    product4_benefits_body: 'Non‑woven fabric (Spunbond) is a lightweight and strong material, which drives its universal use across industries. It is also breathable, allowing air and moisture to pass effectively.',

    // Product 5
    product5_application1: 'Hay Baling',
    product5_application2: 'Binding Plants',
    product5_application3: 'Construction Activities',
    product5_application4: 'General Tying',
    product5_feature1: 'High tensile strength',
    product5_feature2: 'UV resistance',
    product5_feature3: 'Low weight',
    product5_feature4: 'Minimal stretch',
    product5_feature5: 'Long service life',
    product5_longDescription: 'PP twisted ropes (sisal) are suitable for baling and general tying tasks. They are characterized by high tensile strength, UV resistance, and low weight, making them convenient for use in the field and on the farm.',
    product5_benefits_title: 'What are its advantages?',
    product5_benefits_intro: 'Key advantages of polypropylene sisal ropes include:',
    product5_benefits_item1: 'Exceptional strength and resistance to tension',
    product5_benefits_item2: 'Low weight and ease of handling for various needs',
    product5_benefits_item3: 'UV stabilization',
    product5_benefits_item4: 'High resistance to moisture, mold, rot, etc.',
    product5_benefits_item5: 'Choice of color and packaging type, offered in different yarn thicknesses—from 100 m/kg to 1800 m/kg',
    product5_description_title: 'What are they?',
    product5_description_body: 'Polypropylene twisted ropes (sisal) are produced by twisting specially extruded polypropylene tapes. The result is a yarn with high tensile strength that remains lightweight, elastic, and moisture‑resistant. The material does not absorb water, does not mold, and is not affected by weather conditions. This makes it highly reliable for use in agriculture, transport, and industry. The rope is offered in different thicknesses—from very thin to stronger and more durable—depending on the required load and intended use.',
    product5_applications_title: 'Where is it used?',
    product5_applications_body: 'Polypropylene twisted ropes (sisal) are widely used in industries such as agriculture, transport, and general household technical needs. They are primarily used for baling straw, hay, alfalfa, and others—the product is suitable for all baler models.\n\nIn cargo operations, sisal ropes are used for tying and securing loads of various types and volumes. Their use is highly valued in agriculture—in greenhouses and farms. Last but not least, polypropylene sisal is an excellent helper in the packaging and transport industries.',
    product5_specs_label1: 'Material',
    product5_specs_label2: 'UV Protection',
    product5_specs_label3: 'Areas of Use',
    product5_specs_value1: 'PP (polypropylene)',
    product5_specs_value2: 'Yes',
    product5_specs_value3: 'Baling, tying, farming',

    // Product 6
    product6_application1: 'Packaging Solutions',
    product6_application2: 'Building Materials',
    product6_application3: 'Technical Products',
    product6_feature1: 'Eco-friendly choice',
    product6_feature2: 'Optimal price/quality ratio',
    product6_feature3: 'Wide range of applications',
    product6_feature4: 'Recyclable option',
    product6_longDescription: 'Items made from regranulate offer a sustainable solution by reusing polymer materials. They are suitable for various technical and packaging applications, helping to reduce waste and optimize costs.',
    product6_description_title: 'What are they?',
    product6_description_body: 'Regranulate items are made from secondary processed polypropylene and polyethylene, which are melted and granulated, then used to manufacture new products.\n\nThe resulting material has good mechanical properties, high resistance to weather conditions, and is suitable for a wide range of applications. Regranulate products are a preferred solution for technical, auxiliary, and packaging needs because they combine reliability, low cost, and environmental responsibility.',
    product6_applications_title: 'Where is it used?',
    product6_applications_intro: 'Regranulate goods are used in many different areas, the main ones being:',
    product6_applications_item1: 'Household and municipal activities - trash bags/sacks, for example. We offer garbage bags in 5 sizes: 53/60 cm - 35 liters; 55/80 cm - 60 liters; 60/90 cm - 70 liters; 70/90 cm - 80 liters; 70/110 cm - 120 liters;',
    product6_applications_item2: 'In construction - for the production of protective and covering films (we offer a standard roof film roll size – 4x5m (20 sq. m), as well as secondary film on rolls in color or semi-transparent);',
    product6_applications_item3: 'For making packaging and other materials for industrial and warehouse needs such as sleeves and bags, for example.',
    product6_applications_outro: 'Regranulate products are suitable for single or repeated use, depending on thickness and intended purpose.',
    product6_benefits_title: 'What are their advantages?',
    product6_benefits_intro: 'Products made from regranulate stand out with several key advantages, such as:',
    product6_benefits_item1: 'Eco-friendliness and sustainability - recycled material is used in their production, and the products themselves can also be recycled later;',
    product6_benefits_item2: 'Affordable price and good quality - a factor that makes them a preferred choice;',
    product6_benefits_item3: 'Choice among different sizes and thicknesses of the produced items;',
    product6_benefits_item4: 'Wide application - suitable for a variety of uses.',
    product6_specs_label1: 'Material',
    product6_specs_label2: 'Advantages',
    product6_specs_label3: 'Applications',
    product6_specs_value1: 'Recycled polymer (regranulate)',
    product6_specs_value2: 'Eco-friendly, price/quality',
    product6_specs_value3: 'Packaging, construction, technical products',

    productPageHeader: 'We manufacture a wide range of products in the field of polyethylene packaging and polypropylene packaging materials.',
    noProductsFound: 'No products found',
    tryAnotherCategory: 'Try different search criteria',
    characteristics: 'Main Characteristics',
    applications: 'Applications',

    breadcrumb_products: 'Products',
    contact_box_text: 'If you want to contact us:',
    send_inquiry: 'Send inquiry',
    description: 'Description',
    read_more: 'Read more',
    read_less: 'Show less',
    image_index_label: 'Image %s',

    inquiry_prefill: 'Hello,\n\nI am interested in the product: %s\n\nPlease send me more information about prices, availability, and delivery terms.\n\nThank you!',
    inquiry_success: 'Your inquiry was sent successfully! We will contact you soon.',

    inquiry_for: 'Inquiry for: ',
    cancel: 'Cancel',
    inquiry: 'Inquiry',
    details: 'Details',
};

export default translations;