export type Translations = typeof translations;

const translations = {
    // Navbar
    aboutUs: 'About Us',
    news: 'News',
    products: 'Products',
    contacts: 'Contacts',
    shop: 'Shop',
    // HomePage
    homePageHeader: "Leading company in the production of polymer packaging",
    homePageDescription: "Founded in 1991, today 'HIK-91' is a leading company in the production of polymer packaging.",
    contactUs: "Contact Us",
    ourProducts: "Our Products",
    ourProductsDescription: "Discover our full range of high-quality polymer products designed for various industrial applications.",
    ourProductsButton: "View All Products",

    product1_name: 'AGROLEN® Three-Layer Polyethylene Greenhouse Film',
    product1_description: 'AGROLEN® is a high-quality three-layer polyethylene film designed for professional greenhouses. Provides excellent light transmission, optimal microclimate, and high resistance to weather conditions. Suitable for year-round use and effective crop protection.',
    product1_features: 'UV stabilization for long life, Optimal light transmission, Anti-condensation effect (anti-drip), Increased mechanical strength, Improved thermal insulation',
    product1_applications: 'Greenhouses, Tunnels, Winter gardens, Crop protection',
    product1_category: 'Greenhouses',
    product2_name: 'Polyethylene Films and Packaging',
    product2_description: 'We produce a wide range of polyethylene films and packaging for industry, agriculture, and construction. Different thicknesses, widths, and configurations are available, including sleeves, half-sleeves, and sheets.',
    product2_features: 'Variety of formats (sleeve/half-sleeve/sheet), Printing and perforation options, Different thicknesses and widths, High chemical resistance, Custom sizes',
    product2_applications: 'Industrial packaging, Palletizing, Construction, Agriculture, Logistics',
    product2_category: 'Packaging',
    product3_name: 'Polypropylene Woven Bags',
    product3_description: 'Durable woven polypropylene bags for safe transport and storage of bulk materials. Suitable for agriculture, construction, and industry, with various sizes and printing options.',
    product3_features: 'High mechanical strength, Low weight, Reusable, Lamination and printing options, Various sizes',
    product3_applications: 'Grains, Feed, Construction materials, Chemicals, Fertilizers',
    product3_category: 'Bags',
    product4_name: 'Non-Woven Fabric – Spunbond',
    product4_description: 'Non-woven fabric (spunbond) with high permeability and durability, designed for crop protection and construction applications. Suitable for mulching and weed control.',
    product4_features: 'High permeability, UV stabilization, Lightweight construction, Tear-resistant, Easy installation',
    product4_applications: 'Mulching, Weed control, Frost protection, Geotextile, Filtration',
    product4_category: 'Nonwoven fabric',
    product5_name: 'Polypropylene Twisted Ropes',
    product5_description: 'Polypropylene twisted ropes with high strength and UV resistance, designed for baling and tying. Suitable for agriculture and other applications requiring reliability.',
    product5_features: 'High tensile strength, UV resistant, Low weight, Low stretch, Long service life',
    product5_applications: 'Hay baling, Plant tying, Construction, General tying',
    product5_category: 'Ropes',
    product6_name: 'Regranulate Products',
    product6_description: 'Eco-friendly products made from regranulate, combining lower cost with good quality. Suitable for various applications and reducing waste.',
    product6_features: 'Eco-friendly choice, Optimal price/quality ratio, Wide range of applications, Recyclable',
    product6_applications: 'Packaging solutions, Construction materials, Technical products',
    product6_category: 'Regranulate',

    testimonial1_content: "I am extremely satisfied with the quality and fast delivery! I recommend it to every farmer.",
    testimonial1_author: "Ivan Petrov",
    testimonial1_role: "Farmer",
    testimonial2_content: "The products are really durable and practical. The service was top-notch!",
    testimonial2_author: "Maria Georgieva",
    testimonial2_role: "Greenhouse Owner",
    testimonial3_content: "I am happy with the prices and the personal attention. I will order again!",
    testimonial3_author: "Georgi Dimitrov",
    testimonial3_role: "Customer",
    testimonial4_content: "Fast delivery and excellent service! I will recommend it to my colleagues.",
    testimonial4_author: "Stefka Ivanova",
    testimonial4_role: "Farmer",
    testimonial5_content: "I am very satisfied with the products and will order again!",
    testimonial5_author: "Petar Kolev",
    testimonial5_role: "Farmer",
    testimonialsHeader: 'What Our Customers Say',
    testimonialsSubHeader: 'Don’t just take our word for it. See what real customers share about our products and service.',
    // Foooter
    quickLinks: 'Quick Links',
    email: 'Email',
    address: 'Address',
    phone: 'Phone',
    ourAddress: 'Sadovo, 15 km from Plovdiv',
    ourRights: '© 2025 HIK-91. All rights reserved.',
    // AboutUsPage
    aboutUsParagraph1: 'Founded in 1991, today "HIK-91" is a leading company in the production of polymer packaging.',
    aboutUsParagraph2: 'Our high commitment to customer requirements and the ability to meet their needs as quickly as possible have enabled the dynamic development of the company over the past few years.',
    aboutUsParagraph3: '"HIK-91" Ltd. offers quality, innovative style, and a professional team. The company has implemented and applies the ISO 9001:2008 Quality Management System, the ISO 22000:2005 Food Safety Management System, and the ISO 14001:2004 Environmental Management System.',

    statCardLabel1: 'Years of Experience',
    statCardLabel2: 'Satisfied Customers',
    statCardLabel3: 'ISO Certificates',

    ourCertificates: 'Our Certificates',
    certificateSubHeader: 'Quality and reliability are at the core of our work',
    certificate1Subtitle: 'Quality Management System',
    certificate1Note: 'We guarantee high quality for all our products and services',
    certificate2Subtitle: 'Food Safety Management System',
    certificate2Note: 'We ensure safety when handling food products',
    certificate3Subtitle: 'Environmental Management System',
    certificate3Note: 'We protect the environment through responsible production',

    timeline1: 'Establishment of "HIK-91"; the company had one extruder for single-layer film.',
    timeline2: 'Started production of single-layer film up to 8m width.',
    timeline3: 'Installation of extruder for polyethylene bags.',
    timeline4: 'Started production of polypropylene ropes (sisal).',
    timeline5: 'Started production of film up to 12m width.',
    timeline6: 'Installation of complete equipment for production of standard PP bags.',
    timeline7: 'Started production of polypropylene woven bags type AD Star®, with printing capability up to 4 colors.',
    timeline8: 'Installation of extruder for polyethylene film; single-layer film replaced by three-layer film up to 14 meters wide.',
    timeline9: 'Installation of equipment for production of three-layer film up to 8m, heavy-grade sisal; installation of heavy-grade looms for producing Big Bags woven fabric.',
    timeline10: 'Installation of a complete recycling line, as well as a machine for polyethylene bags and garbage bags.',
    timeline11: 'Installation of a new line for production of polypropylene ropes (sisal), and increase of recycling capacity.',
    timeline12: 'Start of a new line for nonwoven fabric production (Spunbond), and a new extruder line for multilayer film up to 6 meters wide.',

    //NewsPage
    news1Content: 'The company “HIK-91 - PATSEV & CO” SD has started the implementation of a grant agreement under procedure: BG-RRP-3.004 “Technological Modernization”. The project is carried out with the financial support of the National Recovery and Resilience Plan, co-financed by the European Union.',
    news1File1: 'Download the full text HERE',
    news2Content: 'HIK-91 participates in project № BG16RFOP002-2.077-1361-C01 titled:',
    news2File1: '“Support for medium-sized enterprises to overcome the economic consequences of the COVID-19 pandemic”',
    news3Content: '“HIK-91 - PATSEV & CO” SD announces a procedure for selecting a contractor under Art.2 (1) of Decree № 80/09.05.2022 with subject: “Supply, installation and commissioning of an Ultrasonic machine for welding and rewinding nonwoven fabric - 1 unit.” Deadline for submission of offers - 14.12.2022 (23:59).',
    news3SubHeader1: 'Offers are submitted in ISUN, section “E-procurement procedures”:',
    news3File1: 'ISUN – E-procurement procedures',
    news3SubHeader2: 'Application documents (available from the news page):',
    news3File2: 'Public invitation',
    news3File3: 'Requirements',
    news3File4: 'Offer template',
    news3File5: 'Evaluation methodology',
    news3File6: 'EIK declaration',
    news3File7: 'Applicants declaration',
    news3File8: 'Draft execution contract',
    news3File9: 'Annex 2 to execution contract',
    news3File10: 'Technical specification',

    //ContactsPage
    contactQuestions: 'Contact us for inquiries, quotes, and collaboration',
    sendUsMessage: 'Send us a message',
    name: 'Name',
    theme: 'Subject',
    message: 'Message',
    sendMessage: 'Send message',
    yourMessage:'Your message...',
    yourName:'Your Name',
    youCanFindUsHere: 'You can find us here',
    ourOffices: 'Our offices',
    tel: 'tel.:',
    office1: 'Head office - 4122 Sadovo, Agricultural yard, tel.:',
    office2: 'Karnalovo, area "Chukito-2"',
    office2Line2: 'Agrocomplex in Karnalovo — tel.:',
    office3: 'Plovdiv, 2A "Georgi Tringov" St. – tel.:',
    office4: 'Blagoevgrad, 5 Anton Chekhov St.,',
    office4Line2:'Wholesale trade "Pirin Commerce" – tel.:',
    office5: 'Varna, 39 "Kolyo Ficheto" St., warehouse 23 – tel.:',
    chooseTheme: 'Choose a theme',
    theme1: 'General inquiries',
    theme2: 'Product information',
    theme3: 'Pricing and offers',
    theme4: 'Delivery',
    theme5: 'Partnership',
    theme6: 'Other',

    // ProductsPage

    product1_application1: 'Greenhouses',
    product1_application2: 'Tunnels',
    product1_application3: 'Winter Gardens',
    product1_application4: 'Plant Protection',
    product1_feature1: 'UV stabilization for long life',
    product1_feature2: 'Optimal light transmission',
    product1_feature3: 'Anti-condensation effect (anti-drip)',
    product1_feature4: 'Enhanced mechanical durability',
    product1_feature5: 'Improved thermal insulation',
    product1_longDescription: 'AGROLEN® is a three-layer film designed to provide controlled light transmission and stable internal climate in greenhouses. Special additives reduce drip-like condensation (anti-drip), improve light scattering, and increase mechanical durability. It is suitable for vegetable, flower, and seedling production, as well as for covering tunnels and greenhouses.',
    product1_specs_label: 'Structure',
    product1_specs_labe2: 'Light Transmission',
    product1_specs_labe3: 'UV Stabilization',
    product1_specs_labe4: 'Available Widths',
    product1_specs_labe5: 'Application',
    product1_specs_value1: 'Three-layer PE',
    product1_specs_value2: 'High',
    product1_specs_value3: 'Long-lasting',
    product1_specs_value4: 'Upon request',
    product1_specs_value5: 'Greenhouses, tunnels, winter gardens',

    // Product 2
    product2_application1: 'Industrial Packaging',
    product2_application2: 'Palletizing',
    product2_application3: 'Construction Activities',
    product2_application4: 'Agriculture',
    product2_application5: 'Logistics',
    product2_feature1: 'Variety of formats (sleeve/half-sleeve/sheet)',
    product2_feature2: 'Option for printing and perforation',
    product2_feature3: 'Different thicknesses and widths',
    product2_feature4: 'High chemical resistance',
    product2_feature5: 'Custom sizes',
    product2_longDescription: 'Our polyethylene films and packaging are made to specification – sleeve, half-sleeve, or sheet, with the possibility of printing, perforation, and antistatic additives. They are suitable for protecting and packaging items, covering and cladding pallets, temporary shelters, as well as for applications in construction and agriculture.',
    product2_specs_label1: 'Material',
    product2_specs_label2: 'Formats',
    product2_specs_label3: 'Thicknesses',
    product2_specs_label4: 'Options',
    product2_specs_value1: 'LDPE/HDPE upon request',
    product2_specs_value2: 'Sleeve, half-sleeve, sheet',
    product2_specs_value3: 'Upon request',
    product2_specs_value4: 'Printing, perforation, additives',

    // Product 3
    product3_application1: 'Grains',
    product3_application2: 'Animal Feed',
    product3_application3: 'Building Materials',
    product3_application4: 'Chemicals',
    product3_application5: 'Fertilizers',
    product3_feature1: 'High mechanical strength',
    product3_feature2: 'Low weight',
    product3_feature3: 'Reusable',
    product3_feature4: 'Option for lamination and printing',
    product3_feature5: 'Various sizes',
    product3_longDescription: 'PP woven bags are intended for transporting and storing grains and other bulk materials. They are produced in various sizes, with the option for lamination for better moisture protection and printing for content identification. They are distinguished by high strength and good wear resistance.',
    product3_specs_label1: 'Material',
    product3_specs_label2: 'Options',
    product3_specs_label3: 'Sizes',
    product3_specs_label4: 'Application',
    product3_specs_value1: 'PP (woven)',
    product3_specs_value2: 'Lamination, print',
    product3_specs_value3: 'Upon request',
    product3_specs_value4: 'Grains, animal feed, building materials',

    // Product 4
    product4_application1: 'Mulching',
    product4_application2: 'Weed Control',
    product4_application3: 'Frost Protection',
    product4_application4: 'Geotextile',
    product4_application5: 'Filtration',
    product4_feature1: 'High permeability',
    product4_feature2: 'UV stabilization',
    product4_feature3: 'Lightweight construction',
    product4_feature4: 'Tear resistance',
    product4_feature5: 'Easy installation',
    product4_longDescription: 'Nonwoven frost protection fabric (Agril) is a breathable, lightweight, UV-stabilized material that protects plants from freezing, wind, and direct sunlight. It is used for direct covering of beds and crops, allowing air and water to pass through without disrupting the microclimate. It is suitable for both early spring and late autumn production. The material helps reduce plant stress and accelerates growth. Due to good thermal insulation and permeability, it helps maintain stable conditions around the crops.',
    product4_specs_label1: 'Color',
    product4_specs_label2: 'Weight',
    product4_specs_label3: 'UV Protection',
    product4_specs_label4: 'Example Widths',
    product4_specs_label5: 'Typical Roll Length',
    product4_specs_value1: 'White',
    product4_specs_value2: '23 g/m²',
    product4_specs_value3: 'For 1 year',
    product4_specs_value4: '1.6m, 2m, 3.2m, 4m, 6m, 8m, 10m',
    product4_specs_value5: '12m (example)',

    // Product 5
    product5_application1: 'Hay Baling',
    product5_application2: 'Binding Plants',
    product5_application3: 'Construction Activities',
    product5_application4: 'General Tying',
    product5_feature1: 'High tensile strength',
    product5_feature2: 'UV resistance',
    product5_feature3: 'Low weight',
    product5_feature4: 'Minimal stretch',
    product5_feature5: 'Long service life',
    product5_longDescription: 'PP twisted ropes (sisal) are suitable for baling and general tying tasks. They are characterized by high tensile strength, UV resistance, and low weight, making them convenient for use in the field and on the farm.',
    product5_specs_label1: 'Material',
    product5_specs_label2: 'UV Protection',
    product5_specs_label3: 'Areas of Use',
    product5_specs_value1: 'PP (polypropylene)',
    product5_specs_value2: 'Yes',
    product5_specs_value3: 'Baling, tying, farming',

    // Product 6
    product6_application1: 'Packaging Solutions',
    product6_application2: 'Building Materials',
    product6_application3: 'Technical Products',
    product6_feature1: 'Eco-friendly choice',
    product6_feature2: 'Optimal price/quality ratio',
    product6_feature3: 'Wide range of applications',
    product6_feature4: 'Recyclable option',
    product6_longDescription: 'Items made from regranulate offer a sustainable solution by reusing polymer materials. They are suitable for various technical and packaging applications, helping to reduce waste and optimize costs.',
    product6_specs_label1: 'Material',
    product6_specs_label2: 'Advantages',
    product6_specs_label3: 'Applications',
    product6_specs_value1: 'Recycled polymer (regranulate)',
    product6_specs_value2: 'Eco-friendly, price/quality',
    product6_specs_value3: 'Packaging, construction, technical products',

    productPageHeader: 'We manufacture a wide range of products in the field of polyethylene packaging and polypropylene packaging materials.',
    noProductsFound: 'No products found',
    tryAnotherCategory: 'Try different search criteria',
    characteristics: 'Main Characteristics',
    applications: 'Applications',

    breadcrumb_products: 'Products',
    contact_box_text: 'If you want to contact us:',
    send_inquiry: 'Send inquiry',
    description: 'Description',
    read_more: 'Read more',
    read_less: 'Show less',
    image_index_label: 'Image %s',

    inquiry_prefill: 'Hello,\n\nI am interested in the product: %s\n\nPlease send me more information about prices, availability, and delivery terms.\n\nThank you!',
    inquiry_success: 'Your inquiry was sent successfully! We will contact you soon.',

    inquiry_for: 'Inquiry for: ',
    cancel: 'Cancel',
    inquiry: 'Inquiry',
    details: 'Details',
};

export default translations;